Algoritmo "Antecessor"
// Disciplina   : Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula o numero antecessor
// Autor(a)    : Alanis
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis 
numero:real
antecessor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero")
Leia(numero)
antecessor<-numero-1
Escreval("O numero antecessor do valor digitado e:",antecessor)
Fimalgoritmo