Algoritmo "Area do Quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula a area do quadrado e exibe o resultado
// Autor(a)    : Alanis
// Data atual  : 12/09/2022
Var
lado, area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite o lado:")
Leia(lado)
area<-(lado*lado)
Escreval("A area do quadrado e:",area)
Fimalgoritmo