Algoritmo "Area do Circulo"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula a area do circulo e exibe o resultado
// Autor(a)    : Alanis
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis
raio,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Informe o raio:")
Leia(raio)
area<-(raio*raio)
Escreval("A area do circulo e:",area)
Fimalgoritmo