Algoritmo "Sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcular o numero sucessor
// Autor(a)    : Alanis Araujo
// Data atual  : 09/09/2022
Var
// Seção de Declarações das variáveis 
numero:inteiro
sucessor:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero")
Leia(numero)
sucessor<-numero+1
Escreval("O resultado do numero sucessor e:",sucessor)
Fimalgoritmo